-   repo: local
    hooks:
    -   id: isort
        name: isort
        description: A Python utility that sorts imports alphabetically
        entry: pipenv run isort -rc --atomic
        language: system
        types: [python]

    -   id: flake8
        name: Flake8
        description: Python Style Guide Enforcement
        entry: pipenv run flake8
        language: system
        types: [python]

    -   id: black
        name: Black
        description: Uncompromising Python code formatter
        entry: pipenv run black
        language: system
        types: [python]

    -   id: trailing-whitespace
        name: Trailing Space
        entry: pipenv run trailing-whitespace-fixer
        language: system
        types: [non-executable, file, text]

    -   id: end-of-file-fixer
        name: End of Files
        description: Ensures that a file is either empty, or ends with one newline.
        entry: pipenv run end-of-file-fixer
        language: system
        types: [non-executable, file, text]

    -   id: check-merge-conflict
        name: Merge Conflicts
        description: Check for files that contain merge conflict strings.
        entry: pipenv run check-merge-conflict
        language: system
        types: [non-executable, file, text]

    -   id: codespell
        name: Spelling
        description: Checks for common misspellings in text files.
        entry: pipenv run codespell --ignore-words .aspell.en.pws
        language: system
        types: [non-executable, file, text]

    -   id: debug-statements
        name: Debug Statements
        description: Checks that debug statements (pdb, ipdb, pudb) are not imported on commit.
        entry: pipenv run debug-statement-hook
        language: system
        types: [python]
